
/*============================================================================*/	

 
GROUP (

  libgcc.a 
  libc.a
  libm.a
  
  
  libSTM32F1xx.a
  
  libx_libc_GCC_M3.a
  libMicroKernel_GCC_M3.a
  libKernel_GCC_M3.a
  libEMXGUI_GCC_M3.a
  libX_SDK_GCC_M3.a
  
  libsdk_freetype_gcc_m3.a
  libsdk_jpg_gcc_m3.a
  libsdk_png_gcc_m3.a
  
  libAudioPlayer.a
  libImageView.a
  libGamepaper.a
  libChineseChess.a
  libInfoNES.a

)


/**** The End ****/
